version: '3.1'

# Production-like deployment for OpenEMR
# This file provides a more production-ready setup for local testing

services:
  mysql-prod:
    restart: always
    image: mariadb:11.4
    container_name: openemr-mysql-prod
    command: ['mariadbd','--character-set-server=utf8mb4','--innodb-buffer-pool-size=512M']
    ports:
      - "3308:3306"
    volumes:
      - mysql-prod-data:/var/lib/mysql
      - ./config/mysql-prod.cnf:/etc/mysql/conf.d/custom.cnf:ro
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD:-secure_root_pass_2024}
      MYSQL_DATABASE: openemr
      MYSQL_USER: openemr
      MYSQL_PASSWORD: ${MYSQL_PASSWORD:-secure_openemr_pass_2024}
    networks:
      - openemr-prod-net
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      interval: 30s
      timeout: 10s
      retries: 3

  openemr-prod:
    restart: always
    image: openemr/openemr:latest
    container_name: openemr-app-prod
    ports:
      - "8090:80"
      - "8453:443"
    volumes:
      - sites-prod:/var/www/localhost/htdocs/openemr/sites:rw
      - logs-prod:/var/log
    environment:
      MYSQL_HOST: mysql-prod
      MYSQL_ROOT_PASS: ${MYSQL_ROOT_PASSWORD:-secure_root_pass_2024}
      MYSQL_USER: openemr
      MYSQL_PASS: ${MYSQL_PASSWORD:-secure_openemr_pass_2024}
      OE_USER: ${OE_USER:-admin}
      OE_PASS: ${OE_PASS:-secure_admin_pass_2024}
      OPENEMR_DOCKER_ENV_TAG: local-prod-environment
      OPENEMR_SETTING_site_addr_oath: 'https://localhost:8453'
      OPENEMR_SETTING_rest_api: 1
      OPENEMR_SETTING_rest_fhir_api: 1
      # Production security settings
      OPENEMR_SETTING_gbl_force_https: 1
      OPENEMR_SETTING_gbl_login_timeout: 3600
    depends_on:
      mysql-prod:
        condition: service_healthy
    networks:
      - openemr-prod-net
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost/"]
      interval: 30s
      timeout: 10s
      retries: 3

  nginx-prod:
    restart: always
    image: nginx:alpine
    container_name: openemr-nginx-prod
    ports:
      - "8091:80"
      - "8454:443"
    volumes:
      - ./config/nginx-prod.conf:/etc/nginx/nginx.conf:ro
      - ./ssl:/etc/nginx/ssl:ro
      - logs-prod:/var/log/nginx
    depends_on:
      - openemr-prod
    networks:
      - openemr-prod-net

volumes:
  mysql-prod-data:
    name: openemr-mysql-prod-data
  sites-prod:
    name: openemr-sites-prod
  logs-prod:
    name: openemr-logs-prod

networks:
  openemr-prod-net:
    name: openemr-prod-network
    driver: bridge