version: '3.1'

# Local development deployment for OpenEMR
# This file is designed to not conflict with project updates
# Based on the official development-easy setup but customized for local use

services:
  mysql-local:
    restart: always
    image: mariadb:11.4
    container_name: openemr-mysql-local
    command: ['mariadbd','--character-set-server=utf8mb4']
    ports:
      - "${MYSQL_PORT:-3307}:3306"  # MySQL port (configurable)
    volumes:
      - mysql-local-data:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD:-openemr_root_pass}
      MYSQL_DATABASE: ${MYSQL_DATABASE:-openemr}
      MYSQL_USER: ${MYSQL_USER:-openemr}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD:-openemr_user_pass}
    networks:
      - openemr-local-net

  openemr-local:
    restart: always
    image: openemr/openemr:flex
    container_name: openemr-app-local
    ports:
      - "${HTTP_PORT:-8080}:80"    # HTTP port (configurable)
      - "${HTTPS_PORT:-8443}:443"   # HTTPS port (configurable)
    volumes:
      - ..:/openemr:ro
      - ..:/var/www/localhost/htdocs/openemr:rw
      - assets-local:/var/www/localhost/htdocs/openemr/public/assets:rw
      - themes-local:/var/www/localhost/htdocs/openemr/public/themes:rw
      - sites-local:/var/www/localhost/htdocs/openemr/sites:rw
      - nodemodules-local:/var/www/localhost/htdocs/openemr/node_modules:rw
      - vendor-local:/var/www/localhost/htdocs/openemr/vendor:rw
      - logs-local:/var/log
    environment:
      MYSQL_HOST: mysql-local
      MYSQL_ROOT_PASS: ${MYSQL_ROOT_PASSWORD:-openemr_root_pass}
      MYSQL_USER: ${MYSQL_USER:-openemr}
      MYSQL_PASS: ${MYSQL_PASSWORD:-openemr_user_pass}
      OE_USER: ${OE_USER:-admin}
      OE_PASS: ${OE_PASS:-admin_password}
      EASY_DEV_MODE: ${EASY_DEV_MODE:-yes}
      EASY_DEV_MODE_NEW: ${EASY_DEV_MODE_NEW:-yes}
      DEVELOPER_TOOLS: ${DEVELOPER_TOOLS:-yes}
      XDEBUG_ON: ${XDEBUG_ON:-1}
      XDEBUG_PROFILER_ON: ${XDEBUG_PROFILER_ON:-1}
      OPENEMR_DOCKER_ENV_TAG: local-dev-environment
      OPENEMR_SETTING_site_addr_oath: 'https://localhost:${HTTPS_PORT:-8443}'
      OPENEMR_SETTING_rest_api: 1
      OPENEMR_SETTING_rest_fhir_api: 1
      OPENEMR_SETTING_rest_portal_api: 1
    depends_on:
      - mysql-local
    networks:
      - openemr-local-net

  phpmyadmin-local:
    restart: always
    image: phpmyadmin:latest
    container_name: openemr-phpmyadmin-local
    ports:
      - "${PHPMYADMIN_PORT:-8081}:80"
    environment:
      PMA_HOST: mysql-local
      PMA_USER: ${MYSQL_USER:-openemr}
      PMA_PASSWORD: ${MYSQL_PASSWORD:-openemr_user_pass}
    depends_on:
      - mysql-local
    networks:
      - openemr-local-net

volumes:
  mysql-local-data:
    name: openemr-mysql-local-data
  assets-local:
    name: openemr-assets-local
  themes-local:
    name: openemr-themes-local
  sites-local:
    name: openemr-sites-local
  nodemodules-local:
    name: openemr-nodemodules-local
  vendor-local:
    name: openemr-vendor-local
  logs-local:
    name: openemr-logs-local

networks:
  openemr-local-net:
    name: openemr-local-network
    driver: bridge